controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    effort_controllers:
      type: chassis_controllers/RollerWheel

effort_controllers:
  ros__parameters:
    left_front_wheel_name: left_front_wheel_joint
    right_front_wheel_name: right_front_wheel_joint
    left_back_wheel_name: left_back_wheel_joint
    right_back_wheel_name: right_back_wheel_joint
    joints:
      - left_front_wheel_joint
      - right_back_wheel_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort
